[project]
name = "mitene-download"
version = "0.1.0"
description = "Download photos and video from mitene.us"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.11.11",
    "pytz>=2024.2",
]
